# CAMPEONATO
DIAS_COMPETENCIA = 2
DIA_INICIAL = 0
DIA = 1
DESCUENTO_MORAL = 10
DESCUENTO_EXCELENCIA_RESPETO = 0.02
BONIFICACION_MORAL = 20
BONIFICACION_DINERO = 100

# DEPORTES
NIVEL_IMPLEMENTOS_COMPETENCIA = 0.1
PUNTAJE_MINIMO = 0
# riesgos
RIESGO_ATLETISMO = 0.2
RIESGO_CICLISMO = 0.35
RIESGO_GIMNASIA = 0.3
RIESGO_NATACION = 0.25
# requerimentos
REQUERIMIENTO_ATLETISMO = False
REQUERIMIENTO_CICLISMO = True
REQUERIMIENTO_GIMNASIA = True
REQUERIMIENTO_NATACION = False
# calcular ganador
# atl
PONDERADOR_VEL_ATLETISMO = 0.55
PONDERADOR_RES_ATLETISMO = 0.2
PONDERADOR_MORAL_ATLETISMO = 0.25
# cic
PONDERADOR_VEL_CICLISMO = 0.47
PONDERADOR_RES_CICLISMO = 0.36
PONDERADOR_FLEX_CICLISMO = 0.17
# gim
PONDERADOR_FLEX_GIMNASIA = 0.5
PONDERADOR_RES_GIMNASIA = 0.3
PONDERADOR_MORAL_GIMNASIA = 0.2
# nat
PONDERADOR_VEL_NATACION = 0.45
PONDERADOR_RES_NATACION = 0.3
PONDERADOR_FLEX_NATACION = 0.25

# DELEGACIONES
CONT_HABILIDAD_ESP = 1
COSTO_HAB_ESP = 20
MINIMO_MORAL = 0
MAXIMO_MORAL = 100
MINIMO_DINERO = 0
PONDERADOR_ENTRENAMIENTO_IEEE = 1.7
PONDERADOR_COMPRAR_TECNOLOGIA = 1.1
SUMADOR_EXCELENCIA_RESPETO = 0.01
POPULARIDAD_MINIMA_DELEGACION = 0
# excelencia y respeto
MINIMO_EXCELENCIA_RESPETO_IEEE = 0.4
MAXIMO_EXCELENCIA_RESPETO_IEEE = 0.8
MINIMO_EXCELENCIA_RESPETO_DCC = 0.3
MAXIMO_EXCELENCIA_RESPETO_DCC = 0.7
# implementos deportivos
MINIMO_IMPLEMENTOS_DEP_IEEE = 0.3
MAXIMO_IMPLEMENTOS_DEP_IEEE = 0.7
MINIMO_IMPLEMENTOS_DEP_DCC = 0.2
MAXIMO_IMPLEMENTOS_DEP_DCC = 0.6
# implementos medicos
MINIMO_IMPLEMENTOS_MED_IEEE = 0.2
MAXIMO_IMPLEMENTOS_MED_IEEE = 0.6
MINIMO_IMPLEMENTOS_MED_DCC = 0.4
MAXIMO_IMPLEMENTOS_MED_DCC = 0.8
# costos
COSTO_ENTRENAR_DEPORTISTA = 30
COSTO_COMPRAR_TECNOLOGIA = 20
COSTO_SANAR_DEPORTISTA = 30

# DEPORTISTAS
MINIMO_ATRIBUTO_DEPORTISTA = 0
MAXIMO_ATRIBUTO_DEPORTISTA = 100
PUNTOS_ENTRENAMIENTO = 5
